services:
  db:
    image: postgres:16 # usar versiones especificas por si hay beraking changes
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    container_name: fastapi-blog-db
    volumes:
      - ./postgres:/var/lib/postgresql/data